const RESUMOPEDIDO = Cypress.env("CENARIOS")["RESUMOPEDIDO"];
const PEDIDOAUTOMATICO = Cypress.env("CENARIOS")["PEDIDOAUTOMATICO"];
const PEDIDOMANUAL = Cypress.env("CENARIOS")["PEDIDOMANUAL"];
const REVISAOENVIO = Cypress.env("CENARIOS")["REVISAOENVIO"];
const TESTESGERAIS = Cypress.env("CENARIOS")["TESTESGERAIS"];

const RESUMOPEDIDOVERIFICARRESPOSTAS =
    Cypress.env("CENARIOS")["ESPECIFICOS"]["RESUMOPEDIDOVERIFICARRESPOSTAS"];

const USUARIO_DEMO = Cypress.env("LOGIN")["USUARIO_DEMO"];
const SENHA_DEMO = Cypress.env("LOGIN")["SENHA_DEMO"];
const CLIENTE_USUARIO = Cypress.env("LOGIN")["CLIENTE_USUARIO"];
const CLIENTE_SENHA = Cypress.env("LOGIN")["CLIENTE_SENHA"];

const URL_AMPLIFY = Cypress.env("URLS")["URL_AMPLIFY"];
const URL_DEMO = Cypress.env("URLS")["URL_DEMO"];
const URL_AUTH_DEMO = Cypress.env("URLS")["URL_AUTH_DEMO"];
const LOCALHOST_8000 = Cypress.env("URLS")["LOCALHOST_8000"];
const URL_API_TESTES = Cypress.env("URLS")["URL_API_TESTES"];

const ROTA_COTACAO_EM_ANALISE =
    Cypress.env("URLS")["ROTAS"]["ROTA_COTACAO_EM_ANALISE"];
const ROTA_EXCLUIR_REGISTROS =
    Cypress.env("URLS")["ROTAS"]["ROTA_EXCLUIR_REGISTROS"];

const DB_USER = Cypress.env("DB")["DB_USER"];
const DB_PSSWRD = Cypress.env("DB")["DB_PSSWRD"];
const DB_CONNECT_URL = Cypress.env("DB")["DB_CONNECT_URL"];

export {
    RESUMOPEDIDO,
    PEDIDOAUTOMATICO,
    PEDIDOMANUAL,
    REVISAOENVIO,
    TESTESGERAIS,
    RESUMOPEDIDOVERIFICARRESPOSTAS,
    USUARIO_DEMO,
    SENHA_DEMO,
    CLIENTE_USUARIO,
    CLIENTE_SENHA,
    URL_AMPLIFY,
    URL_DEMO,
    URL_AUTH_DEMO,
    DB_USER,
    DB_PSSWRD,
    DB_CONNECT_URL,
    LOCALHOST_8000,
    ROTA_COTACAO_EM_ANALISE,
    ROTA_EXCLUIR_REGISTROS,
    URL_API_TESTES,
};
